package cn.cherish.mboot.dal.vo.admin;
// Generated 2016-8-16 18:02:26 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class UserDto implements java.io.Serializable {

    private static final long serialVersionUID = -3703091209635157421L;


    private Long id;
    private String username;
    private String password;
    private String nickname;
    private String telephone;
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern="yyyy-MM-dd HH:mm:ss", timezone="UTC")
    private Date createtime;
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern="yyyy-MM-dd HH:mm:ss", timezone="UTC")
    private Date modifytime;
    private String active;
    private String description;
    private Long roleId;

    public UserDto() {
    }

    public UserDto(Long id, String username, String nickname, String telephone, Date createtime, Date modifytime, String active, String description, Long roleId) {
        this.id = id;
        this.username = username;
        this.nickname = nickname;
        this.telephone = telephone;
        this.createtime = createtime;
        this.modifytime = modifytime;
        this.active = active;
        this.description = description;
        this.roleId = roleId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public Date getModifytime() {
        return modifytime;
    }

    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    public String getActive() {
        return active;
    }

    public void setActive(String active) {
        this.active = active;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getRoleId() {
        return roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}
